/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#005f71",
        "secondary": "#00687b",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#ffb59b",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#380d00",
        "tertiary-container": "#a33500",
        "surface-container-low": "#f3f3fd",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#191b23",
        "error-container": "#ffdad6",
        "on-surface-variant": "#434654",
        "surface-tint": "#0c56d0",
        "background": "#faf8ff",
        "on-primary-fixed": "#001848",
        "inverse-on-surface": "#f0f0fb",
        "on-tertiary-fixed-variant": "#812800",
        "on-primary-fixed-variant": "#0040a2",
        "on-tertiary-container": "#ffc6b2",
        "primary-fixed": "#dae2ff",
        "on-primary-container": "#c4d2ff",
        "surface-container-highest": "#e1e2ec",
        "surface": "#faf8ff",
        "secondary-container": "#50dcff",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#ffdbcf",
        "on-background": "#191b23",
        "surface-bright": "#faf8ff",
        "secondary-fixed-dim": "#48d7f9",
        "on-secondary-fixed": "#001f27",
        "surface-variant": "#e1e2ec",
        "primary": "#003d9b",
        "outline-variant": "#c3c6d6",
        "surface-dim": "#d9d9e4",
        "surface-container-high": "#e7e7f2",
        "error": "#ba1a1a",
        "inverse-primary": "#b2c5ff",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#b2c5ff",
        "primary-container": "#0052cc",
        "surface-container": "#ededf8",
        "outline": "#737685",
        "tertiary": "#7b2600",
        "secondary-fixed": "#afecff",
        "inverse-surface": "#2e3038",
        "on-secondary-fixed-variant": "#004e5d",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        sm: "8px",
        unit: "4px",
        "container-max": "1200px",
        xs: "4px",
        lg: "24px",
        xl: "32px",
        gutter: "20px",
        md: "16px",
      },
      fontFamily: {
        "body-lg": ["Atkinson Hyperlegible Next", "sans-serif"],
        "display-lg": ["Atkinson Hyperlegible Next", "sans-serif"],
        "body-sm": ["Atkinson Hyperlegible Next", "sans-serif"],
        "label-caps": ["Atkinson Hyperlegible Next", "sans-serif"],
        "headline-md": ["Atkinson Hyperlegible Next", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["15px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
        "display-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["13px", { lineHeight: "1.5", letterSpacing: "0.02em", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "1", letterSpacing: "0.08em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
      boxShadow: {
        premium: "0px 4px 20px rgba(0, 0, 0, 0.04)",
        "premium-hover": "0px 10px 30px rgba(0, 82, 204, 0.08)",
      },
    },
  },
  plugins: [],
};
